stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker compose build
    - docker compose push

deploy:
  stage: deploy
  only: 
    - tags
  script:
    - scp -P 5720 docker-compose.yml s070@10.224.17.96:/srv/services/ths-line-bot/docker-compose.yml
    - ssh -p 5720 s070@10.224.17.96 "cd /srv/services/ths-line-bot && docker compose pull && docker compose up -d"