version: '3.8'

services:
  linebot:
    image: reg.tunghosteel.com/ths_line_bot
    build: .
    volumes:
      - "./logs:/bot/logs"
    ports:
      - "6000:6000"
    environment:
      - PYTHONPATH=.
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - WEBHOOKS_URL_BOT=${WEBHOOKS_URL_BOT}
      - GROUP_ID=${GROUP_ID}
      - LINE_CHANNEL_ACCESS_TOKEN_2=${LINE_CHANNEL_ACCESS_TOKEN_2}
      - LINE_CHANNEL_SECRET_2=${LINE_CHANNEL_SECRET_2}
      - WEBHOOKS_URL_REBAR=${WEBHOOKS_URL_REBAR}
      - LINE_CHANNEL_ACCESS_TOKEN_3=${LINE_CHANNEL_ACCESS_TOKEN_3}
      - LINE_CHANNEL_SECRET_3=${LINE_CHANNEL_SECRET_3}
      - WEBHOOKS_URL_TEST=${WEBHOOKS_URL_TEST}
    container_name: line_bot 
    restart: always
    
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6000", "--reload"]
    
