version: '3.8'

services:
  linebot:
    image: reg.tunghosteel.com/ths_line_bot
    build: .
    ports:
      - "6000:6000"
    environment:
      - PYTHONPATH=.
      - LINE_CHANNEL_ACCESS_TOKEN_TY=${LINE_CHANNEL_ACCESS_TOKEN_TY_TEST}
      - LINE_CHANNEL_SECRET_TY=${LINE_CHANNEL_SECRET_TY_TEST}
      - WEBHOOKS_URL_TY=${WEBHOOKS_URL_TY_TEST}
      
    container_name: line_bot 
    restart: unless-stopped
    
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6000", "--reload"]
    
