version: '3.8'

services:
  linebot:
    image: reg.tunghosteel.com/ths_line_bot
    build: .
    volumes:
      - "./logs:/bot/logs"
    ports:
      - "6000:6000"
    environment:
      - TZ=Asia/Taipei
      - PYTHONPATH=.
      - LINE_CHANNEL_ACCESS_TOKEN_TY_SCRAP=${LINE_CHANNEL_ACCESS_TOKEN_TY_SCRAP}
      - LINE_CHANNEL_SECRET_TY_SCRAP=${LINE_CHANNEL_SECRET_TY_SCRAP}
      - WEBHOOKS_URL_TY_SCRAP=${WEBHOOKS_URL_TY_SCRAP}
      - GROUP_ID_TY_SCRAP=${GROUP_ID_TY_SCRAP}
      - LINE_CHANNEL_ACCESS_TOKEN_PUSHBOT=${LINE_CHANNEL_ACCESS_TOKEN_PUSHBOT}
      - LINE_CHANNEL_SECRET_PUSHBOT=${LINE_CHANNEL_SECRET_PUSHBOT}
      - WEBHOOKS_URL_PUSHBOT=${WEBHOOKS_URL_PUSHBOT}
      - GROUP_ID_PUSHBOT_TY_SCRAP=${GROUP_ID_PUSHBOT_TY_SCRAP}
      - GROUP_ID_PUSHBOT_TY_WATER_SPRAY=${GROUP_ID_PUSHBOT_TY_WATER_SPRAY}
      - LINE_NOTIFY_TOKEN=${LINE_NOTIFY_TOKEN}
      - NTFY_TY_SCRAP=${NTFY_TY_SCRAP}
      - NTFY_WATER_SPRAY=${NTFY_WATER_SPRAY}

    container_name: line_bot
    restart: always

    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6000", "--reload"]
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
      - "./logs:/var/log/linebot:ro"
    environment:
      - "TZ=Asia/Taipei"
      - "config.reload.automatic=true"
    container_name: logstash
    restart: always
    depends_on:
      - linebot
