version: '3.8'

services:
  linebot:
    image: reg.tunghosteel.com/ths_line_bot
    build: .
    volumes:
      - "./logs:/bot/logs"
    ports:
      - "6000:6000"
    environment:
      - PYTHONPATH=.
      - LINE_CHANNEL_ACCESS_TOKEN_TY_SCRAP=${LINE_CHANNEL_ACCESS_TOKEN_TY_SCRAP}
      - LINE_CHANNEL_SECRET_TY_SCRAP=${LINE_CHANNEL_SECRET_TY_SCRAP}
      - WEBHOOKS_URL_TY_SCRAP=${WEBHOOKS_URL_TY_SCRAP}
      - GROUP_ID_TY_SCRAP=${GROUP_ID_TY_SCRAP}
      - LINE_CHANNEL_ACCESS_TOKEN_PUSHBOT=${LINE_CHANNEL_ACCESS_TOKEN_PUSHBOT}
      - LINE_CHANNEL_SECRET_PUSHBOT=${LINE_CHANNEL_SECRET_PUSHBOT}
      - WEBHOOKS_URL_PUSHBOT=${WEBHOOKS_URL_PUSHBOT}
      - GROUP_ID_PUSHBOT=${GROUP_ID_PUSHBOT}
    container_name: line_bot 
    restart: always
    
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6000", "--reload"]
    
